version: 2

# [json, sqlite] - default json
repository: json

# Which economy plugin to use.
# [ BedrockEconomy, Capital]
economy-plugin: BedrockEconomy

# for capital setting.
capital-option:
  selector:
  